/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityIndexRouteImport } from './routes/$city/index'
import { Route as CityCategorySlugRouteImport } from './routes/$city/$categorySlug'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DevImageReviewRouteImport } from './routes/dev/image-review'
import { Route as ServiceLocationsIndexRouteImport } from './routes/service-locations/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/$city/',
  path: '/$city/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCategorySlugRoute = CityCategorySlugRouteImport.update({
  id: '/$city/$categorySlug',
  path: '/$city/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevImageReviewRoute = DevImageReviewRouteImport.update({
  id: '/dev/image-review',
  path: '/dev/image-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceLocationsIndexRoute = ServiceLocationsIndexRouteImport.update({
  id: '/service-locations/',
  path: '/service-locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city/$categorySlug': typeof CityCategorySlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/image-review': typeof DevImageReviewRoute
  '/$city/': typeof CityIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/service-locations/': typeof ServiceLocationsIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$city/$categorySlug': typeof CityCategorySlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/image-review': typeof DevImageReviewRoute
  '/$city': typeof CityIndexRoute
  '/blog': typeof BlogIndexRoute
  '/service-locations': typeof ServiceLocationsIndexRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$city/$categorySlug': typeof CityCategorySlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dev/image-review': typeof DevImageReviewRoute
  '/$city/': typeof CityIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/service-locations/': typeof ServiceLocationsIndexRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city/$categorySlug'
    | '/blog/$slug'
    | '/dev/image-review'
    | '/$city/'
    | '/blog/'
    | '/service-locations/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$city/$categorySlug'
    | '/blog/$slug'
    | '/dev/image-review'
    | '/$city'
    | '/blog'
    | '/service-locations'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/$city/$categorySlug'
    | '/blog/$slug'
    | '/dev/image-review'
    | '/$city/'
    | '/blog/'
    | '/service-locations/'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityCategorySlugRoute: typeof CityCategorySlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DevImageReviewRoute: typeof DevImageReviewRoute
  CityIndexRoute: typeof CityIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServiceLocationsIndexRoute: typeof ServiceLocationsIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/': {
      id: '/$city/'
      path: '/$city'
      fullPath: '/$city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/$categorySlug': {
      id: '/$city/$categorySlug'
      path: '/$city/$categorySlug'
      fullPath: '/$city/$categorySlug'
      preLoaderRoute: typeof CityCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/image-review': {
      id: '/dev/image-review'
      path: '/dev/image-review'
      fullPath: '/dev/image-review'
      preLoaderRoute: typeof DevImageReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-locations/': {
      id: '/service-locations/'
      path: '/service-locations'
      fullPath: '/service-locations/'
      preLoaderRoute: typeof ServiceLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityCategorySlugRoute: CityCategorySlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  DevImageReviewRoute: DevImageReviewRoute,
  CityIndexRoute: CityIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServiceLocationsIndexRoute: ServiceLocationsIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
