/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityIndexRouteImport } from './routes/$city/index'
import { Route as CityCategorySlugRouteImport } from './routes/$city/$categorySlug'
import { Route as DevImageReviewRouteImport } from './routes/dev/image-review'
import { Route as ServiceLocationsIndexRouteImport } from './routes/service-locations/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityIndexRoute = CityIndexRouteImport.update({
  id: '/$city/',
  path: '/$city/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityCategorySlugRoute = CityCategorySlugRouteImport.update({
  id: '/$city/$categorySlug',
  path: '/$city/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevImageReviewRoute = DevImageReviewRouteImport.update({
  id: '/dev/image-review',
  path: '/dev/image-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceLocationsIndexRoute = ServiceLocationsIndexRouteImport.update({
  id: '/service-locations/',
  path: '/service-locations/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city/$categorySlug': typeof CityCategorySlugRoute
  '/dev/image-review': typeof DevImageReviewRoute
  '/$city/': typeof CityIndexRoute
  '/service-locations/': typeof ServiceLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$city/$categorySlug': typeof CityCategorySlugRoute
  '/dev/image-review': typeof DevImageReviewRoute
  '/$city': typeof CityIndexRoute
  '/service-locations': typeof ServiceLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$city/$categorySlug': typeof CityCategorySlugRoute
  '/dev/image-review': typeof DevImageReviewRoute
  '/$city/': typeof CityIndexRoute
  '/service-locations/': typeof ServiceLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city/$categorySlug'
    | '/dev/image-review'
    | '/$city/'
    | '/service-locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$city/$categorySlug'
    | '/dev/image-review'
    | '/$city'
    | '/service-locations'
  id:
    | '__root__'
    | '/'
    | '/$city/$categorySlug'
    | '/dev/image-review'
    | '/$city/'
    | '/service-locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityCategorySlugRoute: typeof CityCategorySlugRoute
  DevImageReviewRoute: typeof DevImageReviewRoute
  CityIndexRoute: typeof CityIndexRoute
  ServiceLocationsIndexRoute: typeof ServiceLocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/': {
      id: '/$city/'
      path: '/$city'
      fullPath: '/$city/'
      preLoaderRoute: typeof CityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city/$categorySlug': {
      id: '/$city/$categorySlug'
      path: '/$city/$categorySlug'
      fullPath: '/$city/$categorySlug'
      preLoaderRoute: typeof CityCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/image-review': {
      id: '/dev/image-review'
      path: '/dev/image-review'
      fullPath: '/dev/image-review'
      preLoaderRoute: typeof DevImageReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-locations/': {
      id: '/service-locations/'
      path: '/service-locations'
      fullPath: '/service-locations/'
      preLoaderRoute: typeof ServiceLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityCategorySlugRoute: CityCategorySlugRoute,
  DevImageReviewRoute: DevImageReviewRoute,
  CityIndexRoute: CityIndexRoute,
  ServiceLocationsIndexRoute: ServiceLocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
